CREATE TABLE `user` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(50) NOT NULL,
    `first_name` VARCHAR(50),
    `last_name` VARCHAR(50),
    `phone_number` VARCHAR(20),
    `user_type` ENUM('ADMIN', 'YOUTH', 'PROVIDER') NOT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
    `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` VARCHAR(50),
    `updated_by` VARCHAR(50),

    PRIMARY KEY (`id`)
);


CREATE TABLE `surveys` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `subjectId` INT NOT NULL,
    `acronym` VARCHAR(50) NOT NULL,
    `expiryDate` TIMESTAMP NOT NULL,
    `formOcc` INT NOT NULL,
    `formCode` VARCHAR(50) NOT NULL,
    `visitOcc` INT NOT NULL,
    `visitID` INT NOT NULL,
    `centreID` VARCHAR(50) NOT NULL,
    `token` VARCHAR(50) NOT NULL,
    `status` ENUM('PENDING', 'INPROGRESS', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);