
export const devUsers = [
  {
    email: "john.doe@example.com",
    firstName: "John",
    lastName: "Doe",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "jane.smith@example.com",
    firstName: "Jane",
    lastName: "Smith",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "michael.brown@example.com",
    firstName: "Michael",
    lastName: "Brown",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "emily.jones@example.com",
    firstName: "Emily",
    lastName: "Jones",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "david.wilson@example.com",
    firstName: "David",
    lastName: "Wilson",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "sarah.davis@example.com",
    firstName: "Sarah",
    lastName: "Davis",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "chris.martin@example.com",
    firstName: "Chris",
    lastName: "Martin",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "lisa.moore@example.com",
    firstName: "Lisa",
    lastName: "Moore",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "james.taylor@example.com",
    firstName: "James",
    lastName: "Taylor",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "patricia.anderson@example.com",
    firstName: "Patricia",
    lastName: "Anderson",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "robert.thomas@example.com",
    firstName: "Robert",
    lastName: "Thomas",
    createdBy: "seed",
    updatedBy: "seed",
  },
  {
    email: "linda.jackson@example.com",
    firstName: "Linda",
    lastName: "Jackson",
    createdBy: "seed",
    updatedBy: "seed",
  },
];
